const images = {
    noImage: require('../image/logo.png'),
    noImage1: require('../image/logo2.png'),
    noImage2: require('../image/logo3.jpg'),
    bell: require('../image/bell.png'),
    bell1: require('../image/Picture1.png'),
    new1: require('../image/new1.png'),
    new2: require('../image/new2.png'),
    new3: require('../image/new3.png'),
    new4: require('../image/new4.png'),
    new5: require('../image/new5.jpg'),
    new6: require('../image/new6.png'),
    new_banner1: require('../image/new-banner1.png'),
    new_banner2: require('../image/new-banner2.png'),
    new_banner3: require('../image/new-banner3.png'),
    new_banner4: require('../image/new-banner4.png'),
    new_banner5: require('../image/new-banner5.png'),
    golden: require('../image/golden.jpg'),
    noImageadmin: require('../image/logo1.png'),
    avataradmin: require('../image/vatatar.jpg'),
    noImage1admin: require('../image/no-image.jpg'),
};
export default images;
